apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: garage-storage
data:
  garage.toml: |
    # Garage Configuration File
    # Replace placeholder values with your actual infrastructure
    
    metadata_dir = "/mnt/meta"
    data_dir = "/mnt/data"
    
    db_engine = "lmdb"
    
    replication_mode = "none"
    
    compression_level = 1
    
    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "127.0.0.1:3901"
    rpc_secret = "CHANGE_ME_TO_RANDOM_64_CHARACTER_HEX_STRING_GENERATE_WITH_OPENSSL"
    
    [s3_api]
    s3_region = "us-east-1"
    api_bind_addr = "[::]:3900"
    root_domain = ".s3.storage-nas.example.com"
    
    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.storage-nas.example.com"
    
    [admin]
    api_bind_addr = "[::]:3903"
    admin_token = "CHANGE_ME_TO_RANDOM_ADMIN_TOKEN_GENERATE_WITH_OPENSSL"
    metrics_token = "CHANGE_ME_TO_RANDOM_METRICS_TOKEN_GENERATE_WITH_OPENSSL"
